UPDATE `lineup`.`SEC_CONSTRAINT` SET `CREATED_BY`=NULL; 
UPDATE `lineup`.`SEC_FILTER` SET `CREATED_BY`=NULL; 
UPDATE `lineup`.`SEC_GROUP` SET `CREATED_BY`=NULL; 
UPDATE `lineup`.`SEC_GROUP_HIERARCHY` SET `CREATED_BY`=NULL; 
UPDATE `lineup`.`SEC_PERMISSION` SET `CREATED_BY`=NULL; 
UPDATE `lineup`.`SEC_ROLE` SET `CREATED_BY`=NULL; 
UPDATE `lineup`.`SEC_SESSION_ATTR` SET `CREATED_BY`=NULL; 
UPDATE `lineup`.`SEC_USER` SET `CREATED_BY`=NULL; 
UPDATE `lineup`.`SEC_USER_ROLE` SET `CREATED_BY`=NULL; 
UPDATE `lineup`.`SEC_USER_SETTING` SET `CREATED_BY`=NULL; 

