alter table LINEUP_AIRPORT add constraint FK_LINEUP_AIRPORT_ON_SITE_CATEGORY foreign key (SITE_CATEGORY_ID) references LINEUP_SITE_CATEGORY(ID);
create index IDX_LINEUP_AIRPORT_ON_SITE_CATEGORY on LINEUP_AIRPORT (SITE_CATEGORY_ID);
