alter table LINEUP_PERIOD_TEMPLATE add constraint FK_LINEUP_PERIOD_TEMPLATE_ON_SITE foreign key (SITE_ID) references LINEUP_SITE(ID);
create index IDX_LINEUP_PERIOD_TEMPLATE_ON_SITE on LINEUP_PERIOD_TEMPLATE (SITE_ID);
