alter table LINEUP_FAVORTITE_TRIPS add constraint FK_LINEUP_FAVORTITE_TRIPS_ON_START_SITE foreign key (START_SITE_ID) references LINEUP_SITE(ID);
alter table LINEUP_FAVORTITE_TRIPS add constraint FK_LINEUP_FAVORTITE_TRIPS_ON_DESTINATION foreign key (DESTINATION_ID) references LINEUP_SITE(ID);
create index IDX_LINEUP_FAVORTITE_TRIPS_ON_START_SITE on LINEUP_FAVORTITE_TRIPS (START_SITE_ID);
create index IDX_LINEUP_FAVORTITE_TRIPS_ON_DESTINATION on LINEUP_FAVORTITE_TRIPS (DESTINATION_ID);
