alter table LINEUP_TRANSFER add constraint FK_LINEUP_TRANSFER_ON_CRAFT_TYPE foreign key (CRAFT_TYPE_ID) references LINEUP_CRAFT_TYPE(ID);
create index IDX_LINEUP_TRANSFER_ON_CRAFT_TYPE on LINEUP_TRANSFER (CRAFT_TYPE_ID);
