alter table LINEUP_TICKET add constraint FK_LINEUP_TICKET_ON_TRANSFER foreign key (TRANSFER_ID) references LINEUP_TRANSFER(ID);
alter table LINEUP_TICKET add constraint FK_LINEUP_TICKET_ON_START_SITE foreign key (START_SITE_ID) references LINEUP_SITE(ID);
alter table LINEUP_TICKET add constraint FK_LINEUP_TICKET_ON_DESTINATION_SITE foreign key (DESTINATION_SITE_ID) references LINEUP_SITE(ID);
alter table LINEUP_TICKET add constraint FK_LINEUP_TICKET_ON_PASSENGER foreign key (PASSENGER_ID) references LINEUP_APP_USER(ID);
create index IDX_LINEUP_TICKET_ON_TRANSFER on LINEUP_TICKET (TRANSFER_ID);
create index IDX_LINEUP_TICKET_ON_START_SITE on LINEUP_TICKET (START_SITE_ID);
create index IDX_LINEUP_TICKET_ON_DESTINATION_SITE on LINEUP_TICKET (DESTINATION_SITE_ID);
create index IDX_LINEUP_TICKET_ON_PASSENGER on LINEUP_TICKET (PASSENGER_ID);
