alter table LINEUP_WAYPOINT add constraint FK_LINEUP_WAYPOINT_ON_PREVIOUS_STANDSTILL foreign key (PREVIOUS_STANDSTILL_ID) references LINEUP_STANDSTILL(ID);
alter table LINEUP_WAYPOINT add constraint FK_LINEUP_WAYPOINT_ON_ID foreign key (ID) references LINEUP_STANDSTILL(ID) on delete CASCADE;
create index IDX_LINEUP_WAYPOINT_ON_PREVIOUS_STANDSTILL on LINEUP_WAYPOINT (PREVIOUS_STANDSTILL_ID);
