alter table LINEUP_SECOND_CLASS add constraint FK_LINEUP_SECOND_CLASS_ON_FIRST_CLASS foreign key (FIRST_CLASS_ID) references LINEUP_FIRST_CLASS(ID);
create index IDX_LINEUP_SECOND_CLASS_ON_FIRST_CLASS on LINEUP_SECOND_CLASS (FIRST_CLASS_ID);
