alter table LINEUP_SITE_ROLE_RULE add constraint FK_LINEUP_SITE_ROLE_RULE_ON_ROLE foreign key (ROLE_ID) references LINEUP_ROLE(ID);
create index IDX_LINEUP_SITE_ROLE_RULE_ON_ROLE on LINEUP_SITE_ROLE_RULE (ROLE_ID);
