alter table LINEUP_WAYPOINT add constraint FK_LINEUP_WAYPOINT_ON_SITE foreign key (SITE_ID) references LINEUP_SITE(ID);
alter table LINEUP_WAYPOINT add constraint FK_LINEUP_WAYPOINT_ON_TRANSFER foreign key (TRANSFER_ID) references LINEUP_TRANSFER(ID);
alter table LINEUP_WAYPOINT add constraint FK_LINEUP_WAYPOINT_ON_NEXT_WAYPOINT foreign key (NEXT_WAYPOINT_ID) references LINEUP_WAYPOINT(ID);
alter table LINEUP_WAYPOINT add constraint FK_LINEUP_WAYPOINT_ON_PREVIOUS_STANDSTILL foreign key (PREVIOUS_STANDSTILL_ID) references LINEUP_STANDSTILL(ID);
create index IDX_LINEUP_WAYPOINT_ON_SITE on LINEUP_WAYPOINT (SITE_ID);
create index IDX_LINEUP_WAYPOINT_ON_TRANSFER on LINEUP_WAYPOINT (TRANSFER_ID);
create index IDX_LINEUP_WAYPOINT_ON_NEXT_WAYPOINT on LINEUP_WAYPOINT (NEXT_WAYPOINT_ID);
create index IDX_LINEUP_WAYPOINT_ON_PREVIOUS_STANDSTILL on LINEUP_WAYPOINT (PREVIOUS_STANDSTILL_ID);
