alter table LINEUP_CERTIFICATE add constraint FK_LINEUP_CERTIFICATE_ON_VERFIED_BY foreign key (VERFIED_BY_ID) references SEC_USER(ID);
create index IDX_LINEUP_CERTIFICATE_ON_VERFIED_BY on LINEUP_CERTIFICATE (VERFIED_BY_ID);
