alter table LINEUP_SITE_ROLE_RULE add constraint FK_LINEUP_SITE_ROLE_RULE_ON_SITE foreign key (SITE_ID) references LINEUP_SITE(ID);
create index IDX_LINEUP_SITE_ROLE_RULE_ON_SITE on LINEUP_SITE_ROLE_RULE (SITE_ID);
