alter table LINEUP_FAVORITE_TRIP add constraint FK_LINEUP_FAVORITE_TRIP_ON_START_SITE foreign key (START_SITE_ID) references LINEUP_SITE(ID);
alter table LINEUP_FAVORITE_TRIP add constraint FK_LINEUP_FAVORITE_TRIP_ON_DESTINATION foreign key (DESTINATION_ID) references LINEUP_SITE(ID);
create index IDX_LINEUP_FAVORITE_TRIP_ON_START_SITE on LINEUP_FAVORITE_TRIP (START_SITE_ID);
create index IDX_LINEUP_FAVORITE_TRIP_ON_DESTINATION on LINEUP_FAVORITE_TRIP (DESTINATION_ID);
