alter table LINEUP_DEPARTMENT add constraint FK_LINEUP_DEPARTMENT_ON_DEPUTY_LEADER foreign key (DEPUTY_LEADER_ID) references LINEUP_APP_USER(ID);
create index IDX_LINEUP_DEPARTMENT_ON_DEPUTY_LEADER on LINEUP_DEPARTMENT (DEPUTY_LEADER_ID);
