alter table LINEUP_SITE add constraint FK_LINEUP_SITE_ON_SITE_CATEGORY foreign key (SITE_CATEGORY_ID) references LINEUP_SITE_CATEGORY(ID);
create index IDX_LINEUP_SITE_ON_SITE_CATEGORY on LINEUP_SITE (SITE_CATEGORY_ID);
