alter table LINEUP_AIRPORT add constraint FK_LINEUP_AIRPORT_ON_PARENT_SITE foreign key (PARENT_SITE_ID) references LINEUP_SITE(ID);
alter table LINEUP_AIRPORT add constraint FK_LINEUP_AIRPORT_ON_CATEGORY foreign key (CATEGORY_ID) references LINEUP_SITE_CATEGORY(ID);
alter table LINEUP_AIRPORT add constraint FK_LINEUP_AIRPORT_ON_SITE_TYPE foreign key (SITE_TYPE_ID) references LINEUP_SITE_TYPE(ID);
create index IDX_LINEUP_AIRPORT_ON_PARENT_SITE on LINEUP_AIRPORT (PARENT_SITE_ID);
create index IDX_LINEUP_AIRPORT_ON_CATEGORY on LINEUP_AIRPORT (CATEGORY_ID);
create index IDX_LINEUP_AIRPORT_ON_SITE_TYPE on LINEUP_AIRPORT (SITE_TYPE_ID);
