alter table LINEUP_TRANSFER add constraint FK_LINEUP_TRANSFER_ON_ANCHOR_WAYPOINT foreign key (ANCHOR_WAYPOINT_ID) references LINEUP_ANCHOR_WAYPOINT(ID);
create index IDX_LINEUP_TRANSFER_ON_ANCHOR_WAYPOINT on LINEUP_TRANSFER (ANCHOR_WAYPOINT_ID);
