alter table LINEUP_ANCHOR_WAYPOINT add constraint FK_LINEUP_ANCHOR_WAYPOINT_ON_SITE foreign key (SITE_ID) references LINEUP_SITE(ID);
alter table LINEUP_ANCHOR_WAYPOINT add constraint FK_LINEUP_ANCHOR_WAYPOINT_ON_TRANSFER foreign key (TRANSFER_ID) references LINEUP_TRANSFER(ID);
alter table LINEUP_ANCHOR_WAYPOINT add constraint FK_LINEUP_ANCHOR_WAYPOINT_ON_NEXT_WAYPOINT foreign key (NEXT_WAYPOINT_ID) references LINEUP_WAYPOINT(ID);
create index IDX_LINEUP_ANCHOR_WAYPOINT_ON_SITE on LINEUP_ANCHOR_WAYPOINT (SITE_ID);
create index IDX_LINEUP_ANCHOR_WAYPOINT_ON_TRANSFER on LINEUP_ANCHOR_WAYPOINT (TRANSFER_ID);
create index IDX_LINEUP_ANCHOR_WAYPOINT_ON_NEXT_WAYPOINT on LINEUP_ANCHOR_WAYPOINT (NEXT_WAYPOINT_ID);
