alter table LINEUP_CERTIFICATE add constraint FK_LINEUP_CERTIFICATE_ON_FILE_DATA foreign key (FILE_DATA_ID) references SYS_FILE(ID);
create index IDX_LINEUP_CERTIFICATE_ON_FILE_DATA on LINEUP_CERTIFICATE (FILE_DATA_ID);
