alter table LINEUP_CERTIFICATE add constraint FK_LINEUP_CERTIFICATE_ON_APP_USER foreign key (APP_USER_ID) references LINEUP_APP_USER(ID);
create index IDX_LINEUP_CERTIFICATE_ON_APP_USER on LINEUP_CERTIFICATE (APP_USER_ID);
