alter table LINEUP_STANDSTILL add constraint FK_LINEUP_STANDSTILL_ON_SITE foreign key (SITE_ID) references LINEUP_SITE(ID);
alter table LINEUP_STANDSTILL add constraint FK_LINEUP_STANDSTILL_ON_TRANSFER foreign key (TRANSFER_ID) references LINEUP_TRANSFER(ID);
alter table LINEUP_STANDSTILL add constraint FK_LINEUP_STANDSTILL_ON_NEXT_WAYPOINT foreign key (NEXT_WAYPOINT_ID) references LINEUP_WAYPOINT(ID);
create index IDX_LINEUP_STANDSTILL_ON_SITE on LINEUP_STANDSTILL (SITE_ID);
create index IDX_LINEUP_STANDSTILL_ON_TRANSFER on LINEUP_STANDSTILL (TRANSFER_ID);
create index IDX_LINEUP_STANDSTILL_ON_NEXT_WAYPOINT on LINEUP_STANDSTILL (NEXT_WAYPOINT_ID);
