alter table LINEUP_STANDSTILL change column CRAFT_TYPE_ID CRAFT_TYPE_ID__U23187 varchar(32)^
alter table LINEUP_STANDSTILL change column MODE_OF_TRANSFER_ID MODE_OF_TRANSFER_ID__U20029 varchar(32)^
alter table LINEUP_STANDSTILL change column OPERATED_BY_ID OPERATED_BY_ID__U22356 varchar(32)^
alter table LINEUP_STANDSTILL change column CREW_CHANGE_ID CREW_CHANGE_ID__U23850 varchar(32)^
alter table LINEUP_STANDSTILL change column TRANSFER_ORDER_NO TRANSFER_ORDER_NO__U84043 int^
alter table LINEUP_STANDSTILL modify column TRANSFER_ORDER_NO__U84043 int null ;
alter table LINEUP_STANDSTILL change column STOPOVER_TIME STOPOVER_TIME__U88576 int^
alter table LINEUP_STANDSTILL change column PREVIOUS_STANDSTILL_ID PREVIOUS_STANDSTILL_ID__U56393 varchar(32)^
alter table LINEUP_STANDSTILL change column TAKE_OFF TAKE_OFF__U16031 time^
alter table LINEUP_STANDSTILL change column START_DATE_TIME START_DATE_TIME__U32111 datetime^
alter table LINEUP_STANDSTILL change column DTYPE DTYPE__U60817 varchar(100)^
