alter table LINEUP_TRANSFER drop column VERSION__U49347 cascade ;
alter table LINEUP_TRANSFER drop column CREATE_TS__U46895 cascade ;
alter table LINEUP_TRANSFER drop column CREATED_BY__U27183 cascade ;
alter table LINEUP_TRANSFER drop column UPDATE_TS__U64533 cascade ;
alter table LINEUP_TRANSFER drop column UPDATED_BY__U55659 cascade ;
alter table LINEUP_TRANSFER drop column DELETE_TS__U44031 cascade ;
alter table LINEUP_TRANSFER drop column DELETED_BY__U63562 cascade ;
alter table LINEUP_TRANSFER drop column SITE_ID__U52002 cascade ;
alter table LINEUP_TRANSFER drop column TRANSFER_ID__U86261 cascade ;
