alter table LINEUP_SITE_TYPE add constraint FK_LINEUP_SITE_TYPE_ON_PARENT_TYPE foreign key (PARENT_TYPE_ID) references LINEUP_SITE_TYPE(ID);
create index IDX_LINEUP_SITE_TYPE_ON_PARENT_TYPE on LINEUP_SITE_TYPE (PARENT_TYPE_ID);
