alter table LINEUP_PAYLOAD add constraint FK_LINEUP_PAYLOAD_ON_CRAFT_TYPE foreign key (CRAFT_TYPE_ID) references LINEUP_CRAFT_TYPE(ID);
create index IDX_LINEUP_PAYLOAD_ON_CRAFT_TYPE on LINEUP_PAYLOAD (CRAFT_TYPE_ID);
