alter table LINEUP_WAY add constraint FK_LINEUP_WAY_ON_DEPARTURE_SITE foreign key (DEPARTURE_SITE_ID) references LINEUP_WAYPOINT(ID);
alter table LINEUP_WAY add constraint FK_LINEUP_WAY_ON_ARRIVAL_SITE foreign key (ARRIVAL_SITE_ID) references LINEUP_WAYPOINT(ID);
create index IDX_LINEUP_WAY_ON_DEPARTURE_SITE on LINEUP_WAY (DEPARTURE_SITE_ID);
create index IDX_LINEUP_WAY_ON_ARRIVAL_SITE on LINEUP_WAY (ARRIVAL_SITE_ID);
