alter table LINEUP_WAYPOINT add constraint FK_LINEUP_WAYPOINT_ON_CREW_CHANGE foreign key (CREW_CHANGE_ID) references LINEUP_CREW_CHANGE(ID);
create index IDX_LINEUP_WAYPOINT_ON_CREW_CHANGE on LINEUP_WAYPOINT (CREW_CHANGE_ID);
