alter table LINEUP_TICKET add constraint FK_LINEUP_TICKET_ON_TRANSFER foreign key (TRANSFER_ID) references LINEUP_TRANSFER(ID);
create index IDX_LINEUP_TICKET_ON_TRANSFER on LINEUP_TICKET (TRANSFER_ID);
