alter table LINEUP_WAYPOINT add constraint FK_LINEUP_WAYPOINT_ON_OPERATED_BY foreign key (OPERATED_BY_ID) references LINEUP_COMPANY(ID);
create index IDX_LINEUP_WAYPOINT_ON_OPERATED_BY on LINEUP_WAYPOINT (OPERATED_BY_ID);
