alter table LINEUP_FAVORITE_TRIP add constraint FK_LINEUP_FAVORITE_TRIP_ON_DESTINATION foreign key (DESTINATION_ID) references LINEUP_SITE(ID);
create index IDX_LINEUP_FAVORITE_TRIP_ON_DESTINATION on LINEUP_FAVORITE_TRIP (DESTINATION_ID);
