alter table LINEUP_WAYPOINT add constraint FK_LINEUP_WAYPOINT_ON_CRAFT_TYPE foreign key (CRAFT_TYPE_ID) references LINEUP_CRAFT_TYPE(ID);
create index IDX_LINEUP_WAYPOINT_ON_CRAFT_TYPE on LINEUP_WAYPOINT (CRAFT_TYPE_ID);
