alter table LINEUP_MAIL_NOTIFICATION add constraint FK_LINEUP_MAIL_NOTIFICATION_ON_TRANSFER foreign key (TRANSFER_ID) references LINEUP_TRANSFER(ID);
alter table LINEUP_MAIL_NOTIFICATION add constraint FK_LINEUP_MAIL_NOTIFICATION_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_LINEUP_MAIL_NOTIFICATION_ON_TRANSFER on LINEUP_MAIL_NOTIFICATION (TRANSFER_ID);
create index IDX_LINEUP_MAIL_NOTIFICATION_ON_USER on LINEUP_MAIL_NOTIFICATION (USER_ID);
