alter table LINEUP_TICKET add constraint FK_LINEUP_TICKET_ON_DESTINATION_SITE foreign key (DESTINATION_SITE_ID) references LINEUP_SITE(ID);
create index IDX_LINEUP_TICKET_ON_DESTINATION_SITE on LINEUP_TICKET (DESTINATION_SITE_ID);
