alter table LINEUP_STANDSTILL add constraint FK_LINEUP_STANDSTILL_ON_NEXT_WAYPOINT foreign key (NEXT_WAYPOINT_ID) references LINEUP_WAYPOINT(ID);
create index IDX_LINEUP_STANDSTILL_ON_NEXT_WAYPOINT on LINEUP_STANDSTILL (NEXT_WAYPOINT_ID);
