alter table LINEUP_WAYPOINT add constraint FK_LINEUP_WAYPOINT_ON_NEXT_WAYPOINT foreign key (NEXT_WAYPOINT_ID) references LINEUP_WAYPOINT(ID);
create index IDX_LINEUP_WAYPOINT_ON_NEXT_WAYPOINT on LINEUP_WAYPOINT (NEXT_WAYPOINT_ID);
