alter table LINEUP_TICKET add constraint FK_LINEUP_TICKET_ON_TRAVEL_OPTION foreign key (TRAVEL_OPTION_ID) references LINEUP_TRAVEL_OPTION(ID);
create index IDX_LINEUP_TICKET_ON_TRAVEL_OPTION on LINEUP_TICKET (TRAVEL_OPTION_ID);
