alter table LINEUP_STANDSTILL add constraint FK_LINEUP_STANDSTILL_ON_TRANSFER foreign key (TRANSFER_ID) references LINEUP_TRANSFER(ID);
create index IDX_LINEUP_STANDSTILL_ON_TRANSFER on LINEUP_STANDSTILL (TRANSFER_ID);
