alter table LINEUP_TRAVEL_OPTION add constraint FK_LINEUP_TRAVEL_OPTION_ON_TRANSFER foreign key (TRANSFER_ID) references LINEUP_TRANSFER(ID);
alter table LINEUP_TRAVEL_OPTION add constraint FK_LINEUP_TRAVEL_OPTION_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_LINEUP_TRAVEL_OPTION_ON_TRANSFER on LINEUP_TRAVEL_OPTION (TRANSFER_ID);
create index IDX_LINEUP_TRAVEL_OPTION_ON_USER on LINEUP_TRAVEL_OPTION (USER_ID);
