alter table LINEUP_TRANSFER add constraint FK_LINEUP_TRANSFER_ON_HEAD_WAYPOINT foreign key (HEAD_WAYPOINT_ID) references LINEUP_WAYPOINT(ID);
create index IDX_LINEUP_TRANSFER_ON_HEAD_WAYPOINT on LINEUP_TRANSFER (HEAD_WAYPOINT_ID);
