alter table LINEUP_WAYPOINT change column NEXT_WAYPOINT_ID NEXT_WAYPOINT_ID__U59674 varchar(32)^
drop index IDX_LINEUP_WAYPOINT_ON_NEXT_WAYPOINT on LINEUP_WAYPOINT ;
alter table LINEUP_WAYPOINT drop foreign key FK_LINEUP_WAYPOINT_ON_NEXT_WAYPOINT;
alter table LINEUP_WAYPOINT add column POS_ORDER integer ;
