alter table LINEUP_TICKET add constraint FK_LINEUP_TICKET_ON_START_SITE foreign key (START_SITE_ID) references LINEUP_SITE(ID);
create index IDX_LINEUP_TICKET_ON_START_SITE on LINEUP_TICKET (START_SITE_ID);
