alter table LINEUP_TICKET add constraint FK_LINEUP_TICKET_ON_START_WAYPOINT foreign key (START_WAYPOINT_ID) references LINEUP_WAYPOINT(ID);
create index IDX_LINEUP_TICKET_ON_START_WAYPOINT on LINEUP_TICKET (START_WAYPOINT_ID);
