alter table LINEUP_MAINTENANCE_CAMPAIGN add constraint FK_LINEUP_MAINTENANCE_CAMPAIGN_SITE foreign key (SITE_ID) references LINEUP_SITE(ID);
create index IDX_LINEUP_MAINTENANCE_CAMPAIGN_SITE on LINEUP_MAINTENANCE_CAMPAIGN (SITE_ID);
