alter table LINEUP_SITE_PERIOD add constraint FK_LINEUP_SITE_PERIOD_PARENT_PERIOD foreign key (PARENT_PERIOD_ID) references LINEUP_SITE_PERIOD(ID);
create index IDX_LINEUP_SITE_PERIOD_PARENT_PERIOD on LINEUP_SITE_PERIOD (PARENT_PERIOD_ID);
