alter table LINEUP_OUTAGE_PERIOD add constraint FK_LINEUP_OUTAGE_PERIOD_SITE foreign key (SITE_ID) references LINEUP_SITE(ID);
create index IDX_LINEUP_OUTAGE_PERIOD_SITE on LINEUP_OUTAGE_PERIOD (SITE_ID);
