alter table LINEUP_ABSENCE_PERIOD add constraint FK_LINEUP_ABSENCE_PERIOD_ABSENCE_TYPE foreign key (ABSENCE_TYPE_ID) references LINEUP_PERIOD_TYPE(ID);
create index IDX_LINEUP_ABSENCE_PERIOD_ABSENCE_TYPE on LINEUP_ABSENCE_PERIOD (ABSENCE_TYPE_ID);
